# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b6637f1cbaea7ac9d84b7b6a476a5eb0bb1b94c331075c380b85cac8a1a3903a72e256c0119f2342c36a1c0c2642e936c40658d2fa8da8976ec4364be2cb212

test:
  secret_key_base: 8877df57ddba38f05449f2ac9738073bb448e8bcc8f8e35ad7dc330bf9d73052f28777c7d08428a183e0109d200f584eab2990e7fa2ab3b230427f8a619105b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
